name: Validate Commit Message
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  pull-requests: read
jobs:
  pr-commits:
    name: Validate Pull Request Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Commits
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^([Rr]evert )?((minor|fix|config|infra|ci|doc|spelling|dependency)|[A-Z]{2,14}-\d+): (.*){128}$'
          error: 'Commit messages must match ^([Rr]evert )?((minor|fix|config|infra|ci|doc|spelling|dependency)|[A-Z]{2,14}-\\d+): (.*){128}$'
          excludeDescription: 'true' 
          excludeTitle: 'true' 
          checkAllCommitMessages: 'true' 
          accessToken: ${{ secrets.GITHUB_TOKEN }}
